/*
 * Copyright (c) 2014, Oculus VR, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

// DO NOT EDIT THIS FILE, CHANGES WILL BE LOST WHEN UPDATING RAKNET.
// See NativeFeatureIncludesOverrides.h if you wish to change these defines.

#ifndef RAKNET_NATIVE_FEATURE_INCLDUES_H
#define RAKNET_NATIVE_FEATURE_INCLDUES_H

#include "NativeFeatureIncludesOverrides.h"

#ifndef LIBCAT_SECURITY
#define LIBCAT_SECURITY 0
#endif

#ifndef RAKNET_SUPPORT_ConnectionGraph2
#define RAKNET_SUPPORT_ConnectionGraph2       1
#endif
#ifndef RAKNET_SUPPORT_DirectoryDeltaTransfer
#define RAKNET_SUPPORT_DirectoryDeltaTransfer 1
#endif
#ifndef RAKNET_SUPPORT_FileListTransfer
#define RAKNET_SUPPORT_FileListTransfer       1
#endif
#ifndef RAKNET_SUPPORT_FullyConnectedMesh
#define RAKNET_SUPPORT_FullyConnectedMesh     1
#endif
#ifndef RAKNET_SUPPORT_FullyConnectedMesh2
#define RAKNET_SUPPORT_FullyConnectedMesh2    1
#endif
#ifndef RAKNET_SUPPORT_MessageFilter
#define RAKNET_SUPPORT_MessageFilter          1
#endif
#ifndef RAKNET_SUPPORT_NatPunchthroughClient
#define RAKNET_SUPPORT_NatPunchthroughClient  1
#endif
#ifndef RAKNET_SUPPORT_NatPunchthroughServer
#define RAKNET_SUPPORT_NatPunchthroughServer  1
#endif
#ifndef RAKNET_SUPPORT_NatTypeDetectionClient
#define RAKNET_SUPPORT_NatTypeDetectionClient 1
#endif
#ifndef RAKNET_SUPPORT_NatTypeDetectionServer
#define RAKNET_SUPPORT_NatTypeDetectionServer 1
#endif
#ifndef RAKNET_SUPPORT_PacketLogger
#define RAKNET_SUPPORT_PacketLogger           1
#endif
#ifndef RAKNET_SUPPORT_ReadyEvent
#define RAKNET_SUPPORT_ReadyEvent             1
#endif
#ifndef RAKNET_SUPPORT_ReplicaManager3
#define RAKNET_SUPPORT_ReplicaManager3        1
#endif
#ifndef RAKNET_SUPPORT_Router2
#define RAKNET_SUPPORT_Router2                1
#endif
#ifndef RAKNET_SUPPORT_RPC4Plugin
#define RAKNET_SUPPORT_RPC4Plugin             1
#endif
#ifndef RAKNET_SUPPORT_TeamBalancer
#define RAKNET_SUPPORT_TeamBalancer           1
#endif
#ifndef RAKNET_SUPPORT_TeamManager
#define RAKNET_SUPPORT_TeamManager            1
#endif
#ifndef RAKNET_SUPPORT_UDPProxyClient
#define RAKNET_SUPPORT_UDPProxyClient         1
#endif
#ifndef RAKNET_SUPPORT_UDPProxyCoordinator
#define RAKNET_SUPPORT_UDPProxyCoordinator    1
#endif
#ifndef RAKNET_SUPPORT_UDPProxyServer
#define RAKNET_SUPPORT_UDPProxyServer         1
#endif
#ifndef RAKNET_SUPPORT_ConsoleServer
#define RAKNET_SUPPORT_ConsoleServer          1
#endif
#ifndef RAKNET_SUPPORT_RakNetTransport
#define RAKNET_SUPPORT_RakNetTransport        1
#endif
#ifndef RAKNET_SUPPORT_TelnetTransport
#define RAKNET_SUPPORT_TelnetTransport        1
#endif
#ifndef RAKNET_SUPPORT_TCPInterface
#define RAKNET_SUPPORT_TCPInterface           1
#endif
#ifndef RAKNET_SUPPORT_LogCommandParser
#define RAKNET_SUPPORT_LogCommandParser       1
#endif
#ifndef RAKNET_SUPPORT_RakNetCommandParser
#define RAKNET_SUPPORT_RakNetCommandParser    1
#endif
#ifndef RAKNET_SUPPORT_EmailSender
#define RAKNET_SUPPORT_EmailSender            1
#endif
#ifndef RAKNET_SUPPORT_HTTPConnection
#define RAKNET_SUPPORT_HTTPConnection         1
#endif
#ifndef RAKNET_SUPPORT_HTTPConnection2
#define RAKNET_SUPPORT_HTTPConnection2        1
#endif
#ifndef RAKNET_SUPPORT_PacketizedTCP
#define RAKNET_SUPPORT_PacketizedTCP          1
#endif
#ifndef RAKNET_SUPPORT_TwoWayAuthentication
#define RAKNET_SUPPORT_TwoWayAuthentication   1
#endif
#ifndef RAKNET_SUPPORT_CloudClient
#define RAKNET_SUPPORT_CloudClient            1
#endif
#ifndef RAKNET_SUPPORT_CloudServer
#define RAKNET_SUPPORT_CloudServer            1
#endif
#ifndef RAKNET_SUPPORT_DynDNS
#define RAKNET_SUPPORT_DynDNS                 1
#endif
#ifndef RAKNET_SUPPORT_Rackspace
#define RAKNET_SUPPORT_Rackspace              1
#endif
#ifndef RAKNET_SUPPORT_FileOperations
#define RAKNET_SUPPORT_FileOperations         1
#endif
#ifndef RAKNET_SUPPORT_UDPForwarder
#define RAKNET_SUPPORT_UDPForwarder           1
#endif
#ifndef RAKNET_SUPPORT_StatisticsHistory
#define RAKNET_SUPPORT_StatisticsHistory      1
#endif
#ifndef RAKNET_SUPPORT_LibVoice
#define RAKNET_SUPPORT_LibVoice               0
#endif
#ifndef RAKNET_SUPPORT_RelayPlugin
#define RAKNET_SUPPORT_RelayPlugin            1
#endif

/* ensure required dependencies are enabled */
#if     RAKNET_SUPPORT_DirectoryDeltaTransfer == 1
#undef  RAKNET_SUPPORT_FileListTransfer
#define RAKNET_SUPPORT_FileListTransfer 1
#endif
#if     RAKNET_SUPPORT_FullyConnectedMesh2    == 1
#undef  RAKNET_SUPPORT_ConnectionGraph2
#define RAKNET_SUPPORT_ConnectionGraph2 1
#endif
#if     RAKNET_SUPPORT_TelnetTransport        == 1
#undef  RAKNET_SUPPORT_PacketizedTCP
#define RAKNET_SUPPORT_PacketizedTCP    1
#endif
#if     RAKNET_SUPPORT_PacketizedTCP          == 1 || \
        RAKNET_SUPPORT_EmailSender            == 1 || \
        RAKNET_SUPPORT_HTTPConnection         == 1
#undef  RAKNET_SUPPORT_TCPInterface
#define RAKNET_SUPPORT_TCPInterface     1
#endif

#endif /* RAKNET_NATIVE_FEATURE_INCLDUES_H */
